### ISSUE TITLE
Remove unnecessary directories

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-imageclass-app#1]
Please remove following directories from the directory (and add appropriate `.gitignore` patterns):
* .idea
* app/build

(The repo is already 130MB!)

**Comment by YugPatel31** [comment]
Resolved this issue in: https://github.com/waikato-ufdl/ufdl-imageclass-app/commit/76cd67b7a78405322dea78b1e59071202dd9629f
