### ISSUE TITLE
Upload of large images fails

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/ufdl-imageclass-app#2]
@fracpete and @YugPatel31 have identified an issue where uploading a large (~12MP) image to the [backend](https://github.com/waikato-ufdl/ufdl-backend) and immediately trying to set the class of the image fails, stating that the image doesn't exist on the server.

The current work-around is to first upload a small (e.g. 1x1 pixel) image under the desired filename, set the class and then replace it with the actual image.

**Comment by YugPatel31** [comment]
Solved the issue initially using AsyncTask and then RxJava.
