### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-imageclass-app#3]
Add support for offline mode to app, which allows the user to take images, label them, etc without network coverage. Once network coverage is available again, the user can then synchronize the buffered actions with the backend (via a *sync* button).
At this stage, we assume that only one person will work on a single dataset, no need to expect synchronization issues.

**Comment by YugPatel31** [comment]
Added offline mode support in which users can:

- Login via stored credentials 
- Create, edit and delete datasets 
- Capture, upload from gallery, relabel (manual or via auto-classification) and delete images.

When a network connection is available, local usynced datasets will automatically be synced first, followed by unsynced images.
